version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - arnaud.marcille@hotmail.fr
  subject: '[EmptyLine] Build Informations'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true