// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmptyLineExtension22
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmptyLineExtension22.e3b5b1d7-08a7-4dae-8a8b-d730a5d45620";
        public const string Name = "EmptyLine Extension 22";
        public const string Description = @"Visual Studio extension for remove empty lines (more than one consecutive empty line)";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "Rowtips";
        public const string Tags = "Empty Clean lines remove emptyline delete vide ligne supprimer";
    }
}
