// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmptyLineExtension22
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmptyLineExtension22.e3b5b1d7-08a7-4dae-8a8b-d730a5d45620";
        public const string Name = "EmptyLineExtension22";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "METROPOLIS";
        public const string Tags = "";
    }
}
