// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmptyLineExtension22
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EmptyLineExtension22String = "327c4b43-3c29-4458-8754-cd65e2854965";
        public static Guid EmptyLineExtension22 = new Guid(EmptyLineExtension22String);

        public const string guidEmptyLineCommandPackageCmdSetString = "40013f71-5734-44b6-ad7d-2de7ae21de78";
        public static Guid guidEmptyLineCommandPackageCmdSet = new Guid(guidEmptyLineCommandPackageCmdSetString);

        public const string guidImagesString = "1fb91532-2be6-46d2-8215-0db905a13318";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int EmptyLineCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}